spool 03_poblarConceptos.log

prompt PL/SQL Developer import file
prompt Created on jueves, 12 de enero de 2012 by user
set feedback off
set define off
prompt Truncating CONCEPTOSIDENTIFICAR...
truncate table CONCEPTOSIDENTIFICAR;
prompt Loading CONCEPTOSIDENTIFICAR...
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('40', 'NC INTERNET TRANSFERENCIAS ENTRE TERCEROS INTERNET');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('40', 'DEPOSITO AHORROS');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('40', 'NC TES AUT ABONO TRASLADO CENIT');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('52', 'NC TRANS ACH');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('52', 'CRE PAGO PROVEEDOR');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('52', 'NC TRANSF. AVALNET');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('02', 'ABONOS POR A.C.');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('02', 'CONSIGN-AVAL AU');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('02', 'N.C POR TRANSFE');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('02', 'DEPOSITO CUENTA');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('02', 'N.C. OTROS');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('50', 'CONSIGNACION CONVENIO EMPRESARIAL EFECTI');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('50', 'CR MOV RECIBIDO INTERBANCARIO');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('50', 'CREDITO TRASLADO PROPIO TERMI EMPRESARIA');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('50', 'CREDITO PAGO A TERCEROS CTL');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('50', 'CREDITO NOMINA CTL');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('50', 'CR MOV RECIBIDO INTERBANCARIO');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('50', 'CONSIGNACION CONVENIO EMPRESARIAL CANJE');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('52', 'NC TRANSF AUTOMATICA');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('40', 'CREDITO POR TRANSFERENCIA DE CUENTA CORRIENTE');
insert into CONCEPTOSIDENTIFICAR (IDBANCO, CONCEPTO)
values ('02', 'TRANSFERENCIA C');
commit;
prompt 21 records loaded
set feedback on
set define on
prompt Done.

spool off

